services:
  my-kafka-native-producer:
    image: kafka-native-producer:latest
    hostname: producer_$replica
    deploy:
      mode: replicated
      replicas: 2
    environment:
      BOOTSTRAP_SERVERS_CONFIG: broker-1:19092,broker-2:19092,broker-3:19092
      GROUP_ID_CONFIG: test
    depends_on:
      - kafka-topic-initializer-odd
      - kafka-topic-initializer-even




