services:
  my-kafka-native-consumer-odd:
    image: kafka-native-consumer:latest
    deploy:
      mode: replicated
      replicas: 3
    environment:
      BOOTSTRAP_SERVERS_CONFIG: broker-1:19092,broker-2:19092,broker-3:19092
      GROUP_ID_CONFIG: test
      TOPIC_NAME: odd

  my-kafka-native-consumer-even:
    image: kafka-native-consumer:latest
    deploy:
      mode: replicated
      replicas: 2
    environment:
      BOOTSTRAP_SERVERS_CONFIG: broker-1:19092,broker-2:19092,broker-3:19092
      GROUP_ID_CONFIG: test
      TOPIC_NAME: even
  my-kafka-native-consumer-even-1:
    image: kafka-native-consumer:latest
    deploy:
      mode: replicated
      replicas: 2
    environment:
      BOOTSTRAP_SERVERS_CONFIG: broker-1:19092,broker-2:19092,broker-3:19092
      GROUP_ID_CONFIG: other
      TOPIC_NAME: even

  my-kafka-native-consumer-odd-backup:
    image: kafka-native-consumer:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BOOTSTRAP_SERVERS_CONFIG: broker-1:19092,broker-2:19092,broker-3:19092
      GROUP_ID_CONFIG: test_backup
      TOPIC_NAME: odd-backup

