services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: 111
      POSTGRES_USER: 111
  spring-consumer:
    image: orders-listener
    environment:
      spring.kafka.bootstrap-servers: broker-1:19092,broker-2:19092,broker-3:19092
      spring.datasource.url: "jdbc:postgresql://postgres:5432/test"
      spring.datasource.username: 111
      spring.datasource.password: 111
      spring.jpa.hibernate.ddl-auto: create
    depends_on:
      - postgres
  spring-rest:
    image: orders-rest
    ports:
      - 8080:8080
    environment:
      spring.kafka.bootstrap-servers: broker-1:19092,broker-2:19092,broker-3:19092
