services:
  my-kafka-native-consumer-odd:
    image: kafka-native-consumer:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BOOTSTRAP_SERVERS_CONFIG: broker-1:19092,broker-2:19092,broker-3:19092
      APPLICATION_ID_CONFIG: test
      TOPIC_FROM: odd
      TOPIC_TO: odd-backup